"""
Constructor de suites de casos de prueba.
Orquesta los diferentes generadores de técnicas ISTQB.
"""
from typing import List, Optional, Dict, Any
from ..domain.models import TestSuite, SwaggerEndpointData, ISTQBTechnique
from ..domain.interfaces import ITestSuiteBuilder, ITestCaseGenerator


class TestSuiteBuilder(ITestSuiteBuilder):
    """Construye suites de casos de prueba utilizando múltiples generadores."""
    
    def __init__(self, generators: Dict[ISTQBTechnique, ITestCaseGenerator]):
        """
        Inicializa el constructor con los generadores disponibles.
        
        Args:
            generators: Diccionario de generadores por técnica ISTQB
        """
        self.generators = generators
    
    def build(
        self,
        endpoints: List[SwaggerEndpointData],
        techniques: Optional[List[ISTQBTechnique]] = None,
        include_positive: bool = True,
        include_negative: bool = True
    ) -> TestSuite:
        """Construye una suite completa de casos de prueba."""
        
        # Si no se especifican técnicas, usar todas las disponibles
        if techniques is None:
            techniques = list(self.generators.keys())
        
        # Crear la suite
        test_suite = TestSuite(
            name="API Test Suite - Generated by ISTQB Techniques",
            description="Suite de casos de prueba generada automáticamente usando técnicas ISTQB",
            metadata={
                "techniques_applied": [t.value for t in techniques],
                "total_endpoints": len(endpoints),
                "include_positive": include_positive,
                "include_negative": include_negative
            }
        )
        
        # Generar casos de prueba para cada endpoint y técnica
        for endpoint in endpoints:
            for technique in techniques:
                if technique in self.generators:
                    generator = self.generators[technique]
                    test_cases = generator.generate(endpoint)
                    
                    # Filtrar por tipo si es necesario
                    for test_case in test_cases:
                        if (include_positive and test_case.test_type.value == "positive") or \
                           (include_negative and test_case.test_type.value == "negative"):
                            test_suite.add_test_case(test_case)
        
        return test_suite
